name: Project Sync
on:
  issues:
    types:
      - opened
      - reopened
      - closed
jobs:
  sync:
    uses: mauriciogofas/.github/.github/workflows/project-sync.yml@master
    secrets: inherit
