name: Release asset

on:
  release:
    types: [published]

jobs:
  release_asset:
    uses: gofas/.github/.github/workflows/release-asset.yml@master
    with:
      module_name: "gofasquotanotifications"
    secrets: inherit
